config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :repository, only: %i[new index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/repository_controller.rb
# frozen_string_literal: true

class RepositoryController < ApplicationController
  def new
    render 'new', locals: { search: '' }
  end

  def index
    result = Adapters::HttpRequests::Repositories.search(search_param.fetch(:search))

    render 'index', locals: { result: }
  end

  private

  DEFAULT_SEARCH = { search: '' }.freeze

  def search_param
    @search_param = params.permit(:search)
                          .reverse_merge(DEFAULT_SEARCH)
  end
end

app/helpers/adapters/http_requests/repositories.rb
# frozen_string_literal: true

require 'dry/monads'

module Adapters
  module HttpRequests
    class Repositories < Dry::Struct
      include Dry::Monads[:result]

      URL = 'https://api.github.com/search/repositories?q='

      def self.search(params)
        new.search(params)
      end

      def search(params)
        request(params)
      end

      private

      def request(params)
        url = URL + params
        response = conn.get(url)
        return Success(response.body) if response.status == 200

        Failure('Unexpected error.')
      end

      def conn
        Faraday.new do |f|
          f.request :json
          f.response :json
        end
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repository/index.html.erb
<%= render template: 'repository/new', locals: { search: @search_param[:search] } %>
<br>

<% if result.success? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Full name</th>
        <th>Description</th>
        <th>URL</th>
      </tr>
    </thead>
    <tbody>
      <% repositories = result.value! %>
      <% repositories['items'].each do |repository| %>
        <tr>
          <td><%= repository['name'] %></td>
          <td><%= repository['full_name'] %></td>
          <td><%= repository['description'] %></td>
          <td><%= link_to repository['html_url'], repository['html_url']%></a></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  Nothing found. Please, try again.
<% end %>

app/views/repository/new.html.erb
<%= form_with url: repository_index_path, method: :get do |form| %>
  <%= form.label :search, "Search for:" %>
  <%= form.text_field :search, value: search %>
  <%= form.submit "Search" %>
<% end %>